#!/usr/bin/bash
set -euo pipefail

USER=$1
INFLATOR_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/inflate"

if [ ! -f "$INFLATOR_PATH" ]; then
  echo "Error: El archivo $INFLATOR_PATH no existe."
  exit 1
fi

CRON_FILE="/etc/cron.d/inflator"
echo "0 7 * * * $USER $INFLATOR_PATH" | sudo tee $CRON_FILE > /dev/null

sudo chmod 644 $CRON_FILE
sudo chown root:root $CRON_FILE

sudo chmod +x $INFLATOR_PATH

echo "Cron job created at $CRON_FILE to be executed daily at 7:00 AM."