#!/usr/bin/bash
file="../work/working_hard.txt"
date_format="%Y-%m-%d %H:%M:%S"
commits=$1

validate_file() {
    if [ ! -f "$file_path" ]; then
        touch $file
    fi
}

commit_and_push() {
    echo "Leet code at $(date "+$date_format")" >> $file
    git add $file && git commit -m "Leet code at $(date "+$date_format")"
    git push
}

main() {
    validate_file
    local counter=0
    while [ $counter -lt $commits ]; do
        commit_and_push
        counter=$((counter + 1))
    done
}

main


